In [24]:
import numpy as np;
import pandas as pd;
import operator;

In [25]:
def file2matrix(filename):
    rows = 0
    data = []
    with open(filename) as f:
        data = f.readlines()
        rows = len(data)
    return_matrix = np.zeros((rows,3))
    class_vector = []
    if rows > 0:
        index = 0
        for row in data:
            row_split = row.split("\t")
            return_matrix[index,:] = row_split[0:3]
            class_vector.append(row_split[-1].strip())
            index += 1
    return return_matrix, class_vector
#print file2matrix("datingTestSet.txt")[0]

# use pandas to load data
def file2matrix_pandas(filename):
    dt = pd.read_csv("datingTestSet.txt",sep="\t", names=["frequent", "pencentage", "num", "class"])
    return_matrix = dt[["frequent", "pencentage", "num"]].as_matrix()
    class_vector = dt["class"].tolist()
    return return_matrix, class_vector
    
#print file2matrix_pandas("datingTestSet.txt")[0]

In [26]:
def createDataSet():
    group = np.array([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]])
    labels = ['A','A','B','B']
    return group, labels

def classify0(inX, dataSet, labels, k):
    dataSetSize = dataSet.shape[0]
    print dataSet.shape
    print np.tile(inX, (dataSetSize,1))
    diffMat = np.tile(inX, (dataSetSize,1)) - dataSet
    print diffMat
    sqDiffMat = diffMat**2
    print sqDiffMat
    sqDistances = sqDiffMat.sum(axis=1)
    print sqDistances
    distances = sqDistances**0.5
    print distances
    sortedDistIndicies = distances.argsort()
    print sortedDistIndicies
    classCount={}          
    for i in range(k):
        voteIlabel = labels[sortedDistIndicies[i]]
        classCount[voteIlabel] = classCount.get(voteIlabel,0) + 1
    print classCount
    sortedClassCount = sorted(classCount.iteritems(), key=operator.itemgetter(1), reverse=True)
    print sortedClassCount
    return diffMat

group, labels = createDataSet()

classify0([1,1], group, labels, 3)
    

(4L, 2L)
[[1 1]
 [1 1]
 [1 1]
 [1 1]]
[[ 0.  -0.1]
 [ 0.   0. ]
 [ 1.   1. ]
 [ 1.   0.9]]
[[ 0.    0.01]
 [ 0.    0.  ]
 [ 1.    1.  ]
 [ 1.    0.81]]
[ 0.01  0.    2.    1.81]
[ 0.1         0.          1.41421356  1.3453624 ]
[1 0 3 2]
{'A': 2, 'B': 1}
[('A', 2), ('B', 1)]


array([[ 0. , -0.1],
       [ 0. ,  0. ],
       [ 1. ,  1. ],
       [ 1. ,  0.9]])

In [ ]:
z23 = np.zeros((2,3))

In [ ]:
z23.shape

In [ ]:
z23[0,:] = [1,2,3]

In [ ]:
z23

In [ ]:
z23[0, :]