In [48]:
# refer to https://www.cnblogs.com/JZ-Ser/articles/7637845.html

%matplotlib inline
import matplotlib.pyplot as plt;
import numpy as np;
import pandas as pd;
import tensorflow as tf;


In [49]:
#sess = tf.Session();
sess = tf.InteractiveSession();

C:\Users\vincent\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py:1662: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [50]:
x = tf.constant([[1,2,3,4],
                [5,6,7,8],
                [1,3,4,5]]);
x

<tf.Tensor 'Const_12:0' shape=(3, 4) dtype=int32>

In [51]:
y = tf.constant([[1,2,4,1],
                [5,6,8,2],
                [1,3,1,1]]);
tf.transpose(y).eval()

array([[1, 5, 1],
       [2, 6, 3],
       [4, 8, 1],
       [1, 2, 1]])

In [52]:
# matrix mutiplcation
tf.matmul(x, tf.transpose(y)).eval()

array([[ 21,  49,  14],
       [ 53, 133,  38],
       [ 28,  65,  19]])

In [53]:
floatx = tf.constant([[1.,2,3,4],
                [5,6,7,8],
                [1,3,4,5],
                [2,4,4,5]]);

tf.matrix_determinant(floatx).eval()

3.9999995

In [54]:
tf.cast(x, tf.float64).eval()  # convert to another type.

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.],
       [1., 3., 4., 5.]])

In [55]:
tf.matrix_inverse(floatx).eval()

array([[ 0.75      ,  0.24999987, -1.0000004 ,  0.        ],
       [-0.75      , -0.25000003,  0.        ,  1.0000002 ],
       [-2.7499998 ,  0.7500002 ,  3.0000002 , -2.0000005 ],
       [ 2.4999998 , -0.50000006, -2.        ,  1.0000002 ]],
      dtype=float32)

In [56]:
x = tf.constant([[1,2,3,4],
                [1,2,3,4],
                [1,2,3,9]]);
x.eval()

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 9]])

In [57]:
tf.reduce_mean(x).eval()

2

In [58]:
tf.reduce_mean(x, 1).eval()

array([2, 2, 3])

In [59]:
tf.reduce_prod(x, 1).eval()  # 计算一个张量的各个维度上元素的乘积

array([24, 24, 54])

In [60]:
tf.reduce_prod(x, 0).eval()  # 计算一个张量的各个维度上元素的乘积

array([  1,   8,  27, 144])

In [61]:
tf.square(x).eval()

array([[ 1,  4,  9, 16],
       [ 1,  4,  9, 16],
       [ 1,  4,  9, 81]])

In [62]:
s0, s1, s2 = tf.split(x, 3, 0)
s1.eval()

array([[1, 2, 3, 4]])

In [63]:
tf.reduce_sum(x).eval()

35

In [64]:
tf.reduce_sum(x, 0).eval()

array([ 3,  6,  9, 17])

In [65]:
tf.reduce_sum(x, 1).eval()

array([10, 10, 15])

In [66]:
tf.reshape(x, [-1]).eval()

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 9])

In [67]:
tf.reshape(x, [2,-1]).eval()

array([[1, 2, 3, 4, 1, 2],
       [3, 4, 1, 2, 3, 9]])

In [68]:
tf.reshape(x, [-1,6]).eval()

array([[1, 2, 3, 4, 1, 2],
       [3, 4, 1, 2, 3, 9]])

In [69]:
tf.argmin(x, 0).eval()

array([0, 0, 0, 0], dtype=int64)

In [70]:
x.eval()

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 9]])

In [71]:
tf.unique(tf.reshape(x, [-1]))[0].eval()

array([1, 2, 3, 4, 9])

In [72]:
s = tf.constant([1, 2, 1, 3, 1, 1]);
tf.squeeze(s).eval()

array([1, 2, 1, 3, 1, 1])

In [73]:
tf.shape(tf.squeeze(s)).eval()

array([6])

In [74]:
y.eval()

array([[1, 2, 4, 1],
       [5, 6, 8, 2],
       [1, 3, 1, 1]])

In [75]:
tf.concat([x, y], 0).eval()

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 9],
       [1, 2, 4, 1],
       [5, 6, 8, 2],
       [1, 3, 1, 1]])

In [76]:
tf.concat([x, y], 1).eval()

array([[1, 2, 3, 4, 1, 2, 4, 1],
       [1, 2, 3, 4, 5, 6, 8, 2],
       [1, 2, 3, 9, 1, 3, 1, 1]])

In [77]:
tf.truncated_normal([2, 3]).eval()

array([[-0.6275922 ,  1.1750311 , -1.170429  ],
       [-0.07976682,  0.32937527,  1.2229422 ]], dtype=float32)

In [78]:
tf.pow(x, 2).eval()

array([[ 1,  4,  9, 16],
       [ 1,  4,  9, 16],
       [ 1,  4,  9, 81]])

In [81]:
# 行列式

hx = tf.constant([[2,2],
                [1,2]], dtype=tf.float32);
tf.matrix_determinant(hx).eval()

2.0