In [1]:
%matplotlib inline
import matplotlib.pyplot as plt;
import numpy as np;
import pandas as pd;
import tensorflow as tf;


C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [9]:
#sess = tf.Session();
sess = tf.InteractiveSession();

In [10]:
x = tf.constant([[1,2,3,4],
                [5,6,7,8],
                [1,3,4,5]]);
x

<tf.Tensor 'Const_3:0' shape=(3, 4) dtype=int32>

In [11]:
y = tf.constant([[1,2,4,1],
                [5,6,8,2],
                [1,3,1,1]]);
tf.transpose(y).eval()

array([[1, 5, 1],
       [2, 6, 3],
       [4, 8, 1],
       [1, 2, 1]])

In [13]:
# matrix mutiplcation
tf.matmul(x, tf.transpose(y)).eval()

array([[ 21,  49,  14],
       [ 53, 133,  38],
       [ 28,  65,  19]])

In [19]:
floatx = tf.constant([[1.,2,3,4],
                [5,6,7,8],
                [1,3,4,5],
                [2,4,4,5]]);

tf.matrix_determinant(floatx).eval()

3.9999995

In [20]:
tf.matrix_inverse(floatx).eval()

array([[ 0.75      ,  0.24999987, -1.0000004 ,  0.        ],
       [-0.75      , -0.25000003,  0.        ,  1.0000002 ],
       [-2.7499998 ,  0.7500002 ,  3.0000002 , -2.0000005 ],
       [ 2.4999998 , -0.50000006, -2.        ,  1.0000002 ]],
      dtype=float32)