In [2]:
# refer to https://www.cnblogs.com/JZ-Ser/articles/7637845.html

%matplotlib inline
import matplotlib.pyplot as plt;
import numpy as np;
import pandas as pd;
import tensorflow as tf;


/Users/vincent/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
#sess = tf.Session();
sess = tf.InteractiveSession();

In [4]:
x = tf.constant([[1,2,3,4],
                [5,6,7,8],
                [1,3,4,5]]);
x

<tf.Tensor 'Const:0' shape=(3, 4) dtype=int32>

In [5]:
y = tf.constant([[1,2,4,1],
                [5,6,8,2],
                [1,3,1,1]]);
tf.transpose(y).eval()

array([[1, 5, 1],
       [2, 6, 3],
       [4, 8, 1],
       [1, 2, 1]], dtype=int32)

In [6]:
# matrix mutiplcation
tf.matmul(x, tf.transpose(y)).eval()

array([[ 21,  49,  14],
       [ 53, 133,  38],
       [ 28,  65,  19]], dtype=int32)

In [7]:
floatx = tf.constant([[1.,2,3,4],
                [5,6,7,8],
                [1,3,4,5],
                [2,4,4,5]]);

tf.matrix_determinant(floatx).eval()

3.9999995

In [8]:
tf.cast(x, tf.float64).eval()  # convert to another type.

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.],
       [1., 3., 4., 5.]])

In [9]:
tf.matrix_inverse(floatx).eval()

array([[ 0.75      ,  0.24999987, -1.0000004 ,  0.        ],
       [-0.75      , -0.25000003,  0.        ,  1.0000002 ],
       [-2.7499998 ,  0.7500002 ,  3.0000002 , -2.0000005 ],
       [ 2.4999998 , -0.50000006, -2.        ,  1.0000002 ]],
      dtype=float32)

In [10]:
x = tf.constant([[1,2,3,4],
                [1,2,3,4],
                [1,2,3,9]]);
x.eval()

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 9]], dtype=int32)

In [11]:
tf.reduce_mean(x).eval()

2

In [12]:
tf.reduce_mean(x, 1).eval()

array([2, 2, 3], dtype=int32)

In [13]:
tf.square(x).eval()

array([[ 1,  4,  9, 16],
       [ 1,  4,  9, 16],
       [ 1,  4,  9, 81]], dtype=int32)

In [14]:
s0, s1, s2 = tf.split(x, 3, 0)
s1.eval()

array([[1, 2, 3, 4]], dtype=int32)

In [15]:
tf.reduce_sum(x).eval()

35

In [16]:
tf.reduce_sum(x, 0).eval()

array([ 3,  6,  9, 17], dtype=int32)

In [17]:
tf.reduce_sum(x, 1).eval()

array([10, 10, 15], dtype=int32)

In [18]:
tf.reshape(x, [-1]).eval()

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 9], dtype=int32)

In [19]:
tf.reshape(x, [2,-1]).eval()

array([[1, 2, 3, 4, 1, 2],
       [3, 4, 1, 2, 3, 9]], dtype=int32)

In [20]:
tf.reshape(x, [-1,6]).eval()

array([[1, 2, 3, 4, 1, 2],
       [3, 4, 1, 2, 3, 9]], dtype=int32)

In [21]:
tf.argmin(x, 0).eval()

array([0, 0, 0, 0])

In [22]:
x.eval()

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 9]], dtype=int32)

In [23]:
y.eval()

array([[1, 2, 4, 1],
       [5, 6, 8, 2],
       [1, 3, 1, 1]], dtype=int32)

In [24]:
tf.concat([x, y], 0).eval()

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 9],
       [1, 2, 4, 1],
       [5, 6, 8, 2],
       [1, 3, 1, 1]], dtype=int32)

In [25]:
tf.concat([x, y], 1).eval()

array([[1, 2, 3, 4, 1, 2, 4, 1],
       [1, 2, 3, 4, 5, 6, 8, 2],
       [1, 2, 3, 9, 1, 3, 1, 1]], dtype=int32)

In [30]:
tf.truncated_normal([2, 3]).eval()

array([[-0.5791361 ,  0.11214763, -0.24721055],
       [ 0.35599363, -1.9289764 , -0.4898374 ]], dtype=float32)

In [31]:
tf.pow(x, 2).eval()

array([[ 1,  4,  9, 16],
       [ 1,  4,  9, 16],
       [ 1,  4,  9, 81]], dtype=int32)