### Numpy Tutorial Part 1 – Introduction to Arrays
### https://www.machinelearningplus.com/python/numpy-tutorial-part1-array-python-examples/

In [95]:
import numpy as np
print np.__version__

1.11.1


In [96]:
arr1d = np.array([1,2,3,4,5,6,7,8,9])
print type(arr1d)

<type 'numpy.ndarray'>


In [97]:
x = arr1d+2
x.tolist()

[3, 4, 5, 6, 7, 8, 9, 10, 11]

In [98]:
x.shape

(9L,)

In [99]:
arr2 = np.array([[ 1.,  2.,  3.,  4.],
                  [ 3.,  4.,  5.,  6.],
                  [ 5.,  6.,  7.,  8.]])

In [100]:
arr2.shape

(3L, 4L)

In [101]:
arr2.size

12

In [102]:
arr2.ndim

2

In [103]:
arr2[:,:1]

array([[ 1.],
       [ 3.],
       [ 5.]])

In [104]:
arr2[arr2>=4]

array([ 4.,  4.,  5.,  6.,  5.,  6.,  7.,  8.])

In [105]:
# Reverse only the row positions
arr2[::-1, ]

array([[ 5.,  6.,  7.,  8.],
       [ 3.,  4.,  5.,  6.],
       [ 1.,  2.,  3.,  4.]])

In [106]:
# Reverse the row and column positions
arr2[::-1, ::-1]

array([[ 8.,  7.,  6.,  5.],
       [ 6.,  5.,  4.,  3.],
       [ 4.,  3.,  2.,  1.]])

In [107]:
# Insert a nan and an inf
arr2[1,1] = np.nan  # not a number
arr2[1,2] = np.inf  # infinite
arr2

array([[  1.,   2.,   3.,   4.],
       [  3.,  nan,  inf,   6.],
       [  5.,   6.,   7.,   8.]])

In [108]:
# Replace nan and inf with -1. Don't use arr2 == np.nan
missing_bool = np.isnan(arr2) | np.isinf(arr2)
arr2[missing_bool] = -1
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [109]:
# mean, max and min
print arr2.mean()
print arr2.max()
print arr2.min()

3.58333333333
8.0
-1.0


In [110]:
# Row wise and column wise min
print("Column wise minimum: ", np.amin(arr2, axis=0))
print("Row wise minimum: ", np.amin(arr2, axis=1))

('Column wise minimum: ', array([ 1., -1., -1.,  4.]))
('Row wise minimum: ', array([ 1., -1.,  5.]))


In [111]:
# Cumulative Sum
np.cumsum(arr2)

array([  1.,   3.,   6.,  10.,  13.,  12.,  11.,  17.,  22.,  28.,  35.,
        43.])

In [112]:
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 3., -1., -1.,  6.],
       [ 5.,  6.,  7.,  8.]])

In [113]:
# Assign portion of arr2 to arr2a. Doesn't really create a new array.
arr2a = arr2[:2,:2]  
arr2a


array([[ 1.,  2.],
       [ 3., -1.]])

In [114]:
# Assign portion of arr2 to arr2a. Doesn't really create a new array.
arr2a = arr2[:2,:2]  
arr2a[:1, :1] = 200  # 200 will reflect in arr2
arr2

array([[ 200.,    2.,    3.,    4.],
       [   3.,   -1.,   -1.,    6.],
       [   5.,    6.,    7.,    8.]])

In [115]:
# Copy portion of arr2 to arr2b
arr2b = arr2[:2, :2].copy()
arr2b[:1, :1] = 101  # 101 will not reflect in arr2
arr2

array([[ 200.,    2.,    3.,    4.],
       [   3.,   -1.,   -1.,    6.],
       [   5.,    6.,    7.,    8.]])

In [116]:
arr2

array([[ 200.,    2.,    3.,    4.],
       [   3.,   -1.,   -1.,    6.],
       [   5.,    6.,    7.,    8.]])

In [117]:
# Reshape a 3x4 array to 4x3 array
arr2.reshape(4, 3)

array([[ 200.,    2.,    3.],
       [   4.,    3.,   -1.],
       [  -1.,    6.,    5.],
       [   6.,    7.,    8.]])

In [118]:
# Flatten it to a 1d array
arr2.flatten()

array([ 200.,    2.,    3.,    4.,    3.,   -1.,   -1.,    6.,    5.,
          6.,    7.,    8.])

In [119]:
# Changing the flattened array does not change parent
b1 = arr2.flatten()  
b1[0] = 100  # changing b1 does not affect arr2
arr2

array([[ 200.,    2.,    3.,    4.],
       [   3.,   -1.,   -1.,    6.],
       [   5.,    6.,    7.,    8.]])

In [122]:
# Changing the raveled array changes the parent also.
b2 = arr2.ravel()  
b2[0] = 101  # changing b2 changes arr2 also
arr2

array([[ 101.,    2.,    3.,    4.],
       [   3.,   -1.,   -1.,    6.],
       [   5.,    6.,    7.,    8.]])

In [123]:
# Lower limit is 0 be default
print(np.arange(5))  

# 0 to 9
print(np.arange(0, 10))  

# 0 to 9 with step of 2
print(np.arange(0, 10, 2))  

# 10 to 1, decreasing order
print(np.arange(10, 0, -1))

[0 1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[10  9  8  7  6  5  4  3  2  1]


In [124]:
# Start at 1 and end at 50
np.linspace(start=1, stop=50, num=10, dtype=int)

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

In [125]:
# Limit the number of digits after the decimal to 2
np.set_printoptions(precision=2)  

# Start at 10^1 and end at 10^50
np.logspace(start=1, stop=50, num=10, base=10) 

array([  1.00e+01,   2.78e+06,   7.74e+11,   2.15e+17,   5.99e+22,
         1.67e+28,   4.64e+33,   1.29e+39,   3.59e+44,   1.00e+50])

In [126]:
# The np.zeros and np.ones functions lets you create arrays of desired shape where all the items are either 0’s or 1’s.

print(np.zeros([2,2]))
print(np.ones([3,3]))


[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [127]:
# create repeating sequences
a = [1,2,3] 

# Repeat whole of 'a' two times
print('Tile:   ', np.tile(a, 2))

# Repeat each element of 'a' two times
print('Repeat: ', np.repeat(a, 2))

('Tile:   ', array([1, 2, 3, 1, 2, 3]))
('Repeat: ', array([1, 1, 2, 2, 3, 3]))


In [128]:
# Random numbers between [0,1) of shape 2,2
print(np.random.rand(2,2))

# Normal distribution with mean=0 and variance=1 of shape 2,2
print(np.random.randn(2,2))

# Random integers between [0, 10) of shape 2,2
print(np.random.randint(0, 10, size=[2,2]))

# One random number between [0,1)
print(np.random.random())

# Random numbers between [0,1) of shape 2,2
print(np.random.random(size=[2,2]))

# Pick 10 items from a given list, with equal probability
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10))  

# Pick 10 items from a given list with a predefined probability 'p'
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10, p=[0.3, .1, 0.1, 0.4, 0.1]))  # picks more o's

[[ 0.25  0.46]
 [ 0.85  0.19]]
[[-0.2   0.34]
 [-0.57  0.26]]
[[2 5]
 [4 8]]
0.0414184180082
[[ 0.34  0.68]
 [ 0.44  0.43]]
['u' 'o' 'e' 'e' 'u' 'i' 'e' 'e' 'e' 'i']
['o' 'o' 'a' 'u' 'i' 'a' 'a' 'a' 'a' 'i']


In [130]:
# Create the random state
rn = np.random.RandomState(100)

# Create random numbers between [0,1) of shape 2,2
print(rn.rand(2,2))

[[ 0.54  0.28]
 [ 0.42  0.84]]


In [131]:
# Set the random seed
np.random.seed(100)

# Create random numbers between [0,1) of shape 2,2
print(np.random.rand(2,2))

[[ 0.54  0.28]
 [ 0.42  0.84]]


In [133]:
# How to get the unique items and the counts
# Create random integers of size 10 between [0,10)
np.random.seed(100)
arr_rand = np.random.randint(0, 10, size=10)
print(arr_rand)

[8 8 3 7 7 0 4 2 5 2]


In [134]:
# Get the unique items and their counts
uniqs, counts = np.unique(arr_rand, return_counts=True)
print("Unique items : ", uniqs)
print("Counts       : ", counts)

('Unique items : ', array([0, 2, 3, 4, 5, 7, 8]))
('Counts       : ', array([1, 2, 1, 1, 1, 2, 2], dtype=int64))
