In [2]:
import numpy as np

In [3]:
np.random.rand(4,4)

array([[ 0.11331509,  0.61808948,  0.69563363,  0.42199804],
       [ 0.8665531 ,  0.73623926,  0.5410329 ,  0.94972548],
       [ 0.5400627 ,  0.37349349,  0.21055392,  0.89928384],
       [ 0.82457419,  0.96202215,  0.60761409,  0.69646231]])

In [6]:
randMat = np.mat(np.random.rand(4,4))

In [7]:
randMat

matrix([[ 0.29763784,  0.60881461,  0.69852786,  0.85492573],
        [ 0.03778093,  0.1495421 ,  0.79050213,  0.84662473],
        [ 0.76099596,  0.28011335,  0.27151656,  0.97640988],
        [ 0.82448354,  0.14695251,  0.99761654,  0.29189095]])

In [8]:
randMat.I

matrix([[-0.31764582, -0.80063665,  0.77962815,  0.64464396],
        [ 2.37377933, -1.61408049, -0.61435055, -0.21592523],
        [ 0.04318151,  0.63288304, -0.79168289,  0.6861315 ],
        [-0.44543239,  0.91106055,  0.81292595, -0.63127585]])

In [9]:
randMat*randMat.I

matrix([[  1.00000000e+00,  -1.08991127e-16,  -7.23399462e-17,
          -3.60915258e-17],
        [  9.99831528e-17,   1.00000000e+00,  -4.54236673e-17,
          -3.75590409e-17],
        [ -3.16074831e-17,   1.15422118e-16,   1.00000000e+00,
          -2.67420654e-16],
        [ -6.67569615e-17,   3.38093187e-17,   3.24770256e-17,
           1.00000000e+00]])

In [10]:
np.eye(4,4) #单位矩阵

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

# 矩阵乘法

In [24]:
from fractions import Fraction
M = np.matrix([[0,0.5,1,Fraction(1,3)],
               [0.5,0,0,Fraction(1,3)],
               [0.5,0,0,Fraction(1,3)],
               [0,0.5,0,0]])

In [25]:
M

matrix([[0, 0.5, 1, Fraction(1, 3)],
        [0.5, 0, 0, Fraction(1, 3)],
        [0.5, 0, 0, Fraction(1, 3)],
        [0, 0.5, 0, 0]], dtype=object)

In [26]:
V0 = np.matrix([[0.25],
            [0.25],
            [0.25],
            [0.25]])

In [27]:
V0

matrix([[ 0.25],
        [ 0.25],
        [ 0.25],
        [ 0.25]])

In [46]:
vi = V0
for _ in range(1,100000):
    vvv = np.dot(M,vi)
    vi = vvv
print vvv

[[0.39999999999999897]
 [0.23999999999999921]
 [0.23999999999999921]
 [0.11999999999999969]]


In [32]:
V1 = np.dot(M,V0)

In [33]:
V1

matrix([[0.4583333333333333],
        [0.20833333333333331],
        [0.20833333333333331],
        [0.125]], dtype=object)

In [51]:
M1 = np.matrix([[0,0.5,0,Fraction(1,3)],
               [0.5,0,0,Fraction(1,3)],
               [0.5,0,0,Fraction(1,3)],
               [0,0.5,0,0]])
print V0
vi = V0
for _ in range(1,100):
    vvv = np.dot(M1,vi)
    vi = vvv
print vvv

[[ 0.25]
 [ 0.25]
 [ 0.25]
 [ 0.25]]
[[1.3717295483243866e-138]
 [1.3717295483243866e-138]
 [1.3717295483243866e-138]
 [9.411994198708984e-139]]
