In [2]:
from numpy import *

In [3]:
random.rand(4,4)

array([[ 0.45962725,  0.14903692,  0.6384603 ,  0.92816013],
       [ 0.62017859,  0.80117814,  0.26383282,  0.05849769],
       [ 0.58547977,  0.83236329,  0.8413785 ,  0.85245568],
       [ 0.02854683,  0.46616083,  0.0487664 ,  0.63453301]])

In [4]:
randMat = mat(random.rand(4,4))

In [5]:
randMat

matrix([[ 0.9645229 ,  0.44549009,  0.38871534,  0.40317471],
        [ 0.66739534,  0.85777354,  0.20692736,  0.41123127],
        [ 0.09003562,  0.68105207,  0.19886981,  0.09681631],
        [ 0.21703848,  0.93413131,  0.11371432,  0.21332815]])

In [6]:
randMat.I

matrix([[  7.88076015, -13.88335519, -10.45875715,  16.61536464],
        [  2.12352035,  -4.82613614,  -2.90866209,   6.6100717 ],
        [ -3.25452123,   7.62805557,  11.26775493, -13.66747365],
        [-15.58157925,  31.19160886,  17.37098516, -33.87579731]])

In [10]:
randMat*randMat.I

matrix([[  1.00000000e+00,   0.00000000e+00,   2.66453526e-15,
           0.00000000e+00],
        [ -8.88178420e-16,   1.00000000e+00,   0.00000000e+00,
           1.77635684e-15],
        [ -2.22044605e-16,   4.44089210e-16,   1.00000000e+00,
           4.44089210e-16],
        [ -4.44089210e-16,   8.88178420e-16,   1.33226763e-15,
           1.00000000e+00]])

In [13]:
eye(4,4) #单位矩阵

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])