# https://www.kaggle.com/c/digit-recognizer/
# Score: 0.968, number: 1926

In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn.decomposition import PCA
import tensorflow as tf

In [3]:
# load csv files to numpy arrays

def load_data():
    train = pd.read_csv("train.csv")
    print(train.shape)
    X_train = train.values[:,1:] 
    y_train = train.values[:,0]
    
    
    Pred_test = pd.read_csv("test.csv").values
    return X_train, y_train, Pred_test

x_train, y_train, pred_test = load_data()

(42000, 785)


In [4]:
print(x_train.shape, y_train.shape, pred_test.shape)

(42000, 784) (42000,) (28000, 784)


In [5]:

from sklearn.model_selection import train_test_split

# We use this function in order to evaulate a classifier. It trains on a fraction of the data corresponding to 
# aplit_ratio, and evaulates on the rest of the data

def evaluate_classifier(clf, data, target, split_ratio):
    trainX, testX, trainY, testY = train_test_split(data, target, train_size=split_ratio, random_state=0)
    clf.fit(trainX, trainY)
    return clf.score(testX,testY)


In [6]:
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, train_size=0.8, random_state=0)

/Users/vincent/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [10]:
sess = tf.InteractiveSession();

In [14]:
A = tf.constant([1,2,3,1,23,4,67])
top_k_xvals, top_k_indices = tf.nn.top_k(A, k=5)

In [15]:
top_k_xvals.eval()

array([67, 23,  4,  3,  2], dtype=int32)

In [16]:
top_k_indices.eval()

array([6, 4, 5, 2, 1], dtype=int32)

In [18]:
tf.gather(A, top_k_indices).eval()

array([67, 23,  4,  3,  2], dtype=int32)

In [21]:
A = tf.constant([[1,2],
                [1,2]], dtype=tf.float32)
tf.norm(A).eval()

3.1622777

### Without PCA: took 28mins, so the PCA can save time (or memory)

In [26]:
def flush_predictons(predictions):
    imgs = pd.Series(range(1,pred_test.shape[0]+1))
    imgd = pd.DataFrame(imgs)
    
    labeld = pd.DataFrame(predictions)
    out = pd.concat([imgd, labeld],axis=1)
    out.columns = ["ImageId", "Label"]
    out.to_csv("KNN_PCA_Prediction.csv", index = False)

flush_predictons(predictions);

## The Score: 0.97300, better than the KNN without PCA.