# https://www.kaggle.com/c/digit-recognizer/
# with keras + CNN, scored 0.9785714285714285

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split

In [69]:
# load csv files to numpy arrays

def load_data():
    train = pd.read_csv("train.csv")
    X_train = train.values[:,1:] 
    y_train = train.values[:,0]
    
    Pred_test = pd.read_csv("test.csv").values
    return X_train, y_train, Pred_test

def flush_predictons(predictions, output_name='out.csv'):
    '''
    predictions is a np.array of int 
    '''
    imgs = pd.Series(range(1,predictions.shape[0]+1))
    imgd = pd.DataFrame(imgs)
    
    labeld = pd.DataFrame(predictions)
    out = pd.concat([imgd, labeld],axis=1)
    out.columns = ["ImageId", "Label"]
    out.to_csv(output_name, index = False)
    


In [70]:
def merge_results_by_vote(*arg):
    '''
    the shape of arg is (_, 1)
    '''
    
    concat = np.concatenate(*arg, axis=1)
    out = [np.argmax(np.bincount(line)) for line in concat]
    return out

def merge_result(*files):
    '''
    the shape of arg is (_, 1)
    '''
    values = []
    for filename in files:
        v = pd.read_csv(filename).values[:,1]
        v = v.reshape(v.shape[0],1)
        values.append(v)
    
    return merge_results_by_vote(tuple(values))

In [73]:
merge_output = merge_result("keras_cnn.csv", "keras_cnn2.csv", "KNN_tf.csv", "keras_resnet.csv", "KNN_PCA_tf.csv")

In [74]:
flush_predictons(np.array(merge_output), output_name='merge.csv')

In [3]:
output1 = pd.read_csv("keras_cnn.csv").values[:,1]
output2 = pd.read_csv("keras_cnn2.csv").values[:,1]
feature3 = np.concatenate((output1.reshape(output1.shape[0],1), output2.reshape(output2.shape[0],1)), axis=1)



In [24]:
l1 = np.array([1,2,3])
l2 = np.array([0,2,3])

In [25]:
l1+l2

array([1, 4, 6])

In [23]:
len(l1.shape)

1

In [14]:
o = concat_by_column(output1.reshape(output1.shape[0],1), output2.reshape(output2.shape[0],1))

[[2]
 [0]
 [9]
 ...
 [3]
 [9]
 [2]]
[[2]
 [0]
 [9]
 ...
 [3]
 [9]
 [2]]


In [12]:
o.shape

(28000, 2)

In [17]:


o2 = concat_array_by_column(output1, output2)

IndexError: tuple index out of range

In [5]:
print(feature3[0])

[2 2]


In [6]:
l1 = np.array([1,2,3]).reshape(l1.shape[0],1)
l2 = np.array([0,2,3]).reshape(l1.shape[0],1)

NameError: name 'l1' is not defined

In [ ]:
print(np.concatenate((l1, l2), axis=1))

In [ ]:
out = [np.argmax(np.bincount(line)) for line in np.concatenate((l1, l2), axis=1)]
print(out)

In [ ]:
output1.shape

In [ ]:
out = [np.argmax(np.bincount(line)) for line in feature3]

In [ ]:
out

In [ ]:
output.set_index("ImageId").to_dict()["Label"]

In [ ]:
feature1 = pd.DataFrame({'id':[1, 2, 3, 4, 4, 6, 1, 2, 3], 'item1':[1, 2, 3, 4, 5, 6, 1, 2, 3], 'item2':[1, 2, 3, 4, 5, 6, 2, 7, 3]})
feature2 = pd.DataFrame({'id':[1, 3, 7, 4, 4, 6, 1, 2, 3], 'item1':[1, 2, 3, 4, 5, 6, 1, 2, 3], 'item2':[1, 2, 3, 4, 5, 6, 2, 7, 3]})
feature3 = np.concatenate((feature1, feature2),axis = 1)
feature4 = np.concatenate((feature1, feature2),axis = 0)

In [ ]:
feature1

In [ ]:
feature2

In [ ]:
feature3

In [ ]:
feature4

In [ ]:
plt.imshow(pred_test[460].reshape(28, 28))

In [ ]:
flush_predictons(pred, output_name='keras_cnn2.csv')